name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Goto the directory
        run: cd "Hello, World"

      - name: output current dir and contents then Build hello.go
        run: |
          pwd
          ls -l
          go build hello.go

      - name: Test with the Go CLI
        run: go test -v
